# Generated by Django 4.2.5 on 2023-12-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signupform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('RepeatPassword', models.CharField(max_length=150)),
            ],
        ),
    ]
