# Generated by Django 4.2.4 on 2023-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamTitle', models.TextField()),
                ('teamImg', models.TextField()),
                ('employeeName', models.TextField()),
                ('designation', models.TextField()),
            ],
        ),
    ]
