# Generated by Django 4.2.5 on 2023-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whychooseusTitle', models.TextField()),
                ('iconImg', models.TextField()),
                ('titleName', models.TextField()),
                ('descMessage', models.TextField()),
                ('readmoreLink', models.TextField()),
            ],
        ),
    ]
